# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.mp3"
Content-Type: audio/mpeg

< ./1.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name create-transcription
POST http://localhost:3333/videos/493e0fc4-9009-4bdf-bb8e-c397469f8817/transcription
Content-Type: application/json

{
    "prompt": "isekai, waifuu"
}


###
# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "493e0fc4-9009-4bdf-bb8e-c397469f8817",
    "temperature": 0.5,
    "prompt": "Faça um resumo da transcrição a seguir em seguida cite dois animes que abordam temas de escravidão: '''{transcription}'''"
}
